#!/usr/bin/env bash
# craft.sh

_setup() {

    set -Eeuo pipefail
    source "$(dirname "$(readlink -f "$0")")/update.sh"
    trap 'echo "Caught Ctrl+C! Exiting gracefully."; exit 1' SIGINT
    trap 'echo "Caught termination signal! Exiting gracefully."; exit 1' SIGTERM
    trap - ERR EXIT

    SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
    readonly SCRIPT_DIR

    ROOT_SCRIPT="$(basename "$0")"
    readonly ROOT_SCRIPT

    # DEBUG=false
    # DEBUG=true
    # SUPER_DEBUG=false

    source "$SCRIPT_DIR/lib/utils.sh"
    source "$SCRIPT_DIR/lib/logger.sh"
    source "$SCRIPT_DIR/lib/usage.sh"
    source "$SCRIPT_DIR/lib/version.sh"
    source "$SCRIPT_DIR/lib/new_command.sh"

    logger::setup_colors

    utils::need_cmd "docker"
    utils::need_cmd "curl"
    utils::need_cmd "unzip"

}

main() {

    _setup

    update::check_for_updates "$@"

    if [ $# -eq 0 ] || [[ "$1" =~ ^(-h|--help)$ ]]; then
        usage::general
    elif [[ "$1" =~ ^(-v|--version)$ ]]; then
        version::print
        exit 0
    fi

    case "$1" in
    new)
        shift
        new_command::handle_new_command "$@"
        ;;
    *)
        logger::error "Invalid option or command."
        logger::notice "Use '${BINARY_NAME} --help' for usage information."
        exit 1
        ;;
    esac
}

main "$@"
